prepare:
  terminology:
    mesh:
      db:
        host: localhost
        port: 5432
        db: mesh
        user: postgres
        passwd: meshterms

matching:
  score_threshold: 0.7
  cache_threshold: 0.5
  compare_column: Term
  score_func: fuzzy_match
  calculate_tokens: False
  filter_column: Datenbankspalte
  filter_prefix: gec_

gecco_definitions:
  - input/gecco_definition.json

files:
  - input/hap_test.xlsx
  - input/pop_test.xlsx
  - input/suep_test.xlsx
