prepare:
  terminology:
    mesh:
      db:
        host: localhost
        port: 5432
        db: mesh
        user: postgres
        passwd: meshterms

matching:
  score_threshold: 0.7
  cache_threshold: 0.5
  compare_column: Term
  score_func: fuzzy_match
  calculate_tokens: False
  filter_column: Variable
  filter_prefix: gec_
  tokens:
    timeout: 30
    score_threshold: 0.85
  variable_score_threshold: 0.9
  filter_categories: False

steps:
  - variables
  - gecco
  - questionnaires

gecco_definition:
  gecco83: ../napkon-string-matching-data/input/FINAL_GECCO83_DS.xlsx
  geccoplus: ../napkon-string-matching-data/input/20211118_GECCOplus_final.xlsx
  json: ../napkon-string-matching-data/input/input__gecco_definition.json

dataset_definition: ../napkon-string-matching-data/input/dataset_definitions.json

categories_file: ../napkon-string-matching-data/input/categories.json
categories_excel_file: ../napkon-string-matching-data/input/categories.xlsx

files:
  hap: ../napkon-string-matching-data/input/hap_test.xlsx
  pop: ../napkon-string-matching-data/input/pop_test.xlsx
  suep: ../napkon-string-matching-data/input/suep_test.xlsx

table_definitions: ../napkon-string-matching-data/input/table_definitions.json

mappings: ../napkon-string-matching-data/input/mappings/

output_dir: ../napkon-string-matching-data/output
cache_dir: ../napkon-string-matching-data/cache
