prepare:
  terminology:
    mesh:
      db:
        host: localhost
        port: 5432
        db: mesh
        user: postgres
        passwd: meshterms

matching:
  score_threshold: 0.7
  cache_threshold: 0.5
  compare_column: Term
  score_func: fuzzy_match
  calculate_tokens: False
  filter_column: Variable
  filter_prefix: gec_
  tokens:
    timeout: 30
    score_threshold: 0.85
  variable_score_threshold: 0.9

steps:
  - variables
  - gecco
  - questionnaires

gecco_definition:
  gecco83: input/FINAL_GECCO83_DS.xlsx
  geccoplus: input/20211118_GECCOplus_final.xlsx

files:
  hap: input/hap_test.xlsx
  pop: input/pop_test.xlsx
  suep: input/suep_test.xlsx

mappings: input/mappings/
