prepare:
  terminology:
    mesh:
      db:
        host: localhost
        port: 5432
        db: mesh
        user: postgres
        passwd: meshterms
matching:
  score_threshold: 0.7
  cache_threshold: 0.5
  compare_column: Term
  score_func: fuzzy_match
  calculate_tokens: False
  filter_column: Variable
  filter_prefix: gec_
  tokens:
    timeout: 30
    score_threshold: 0.85
  variable_score_threshold: 0.9
  filter_categories: False
steps:
  - variables
  - gecco
  - questionnaires
input:
  base_dir: ../napkon-string-matching-data/input
  gecco_definition:
    gecco83: $input_base_dir/FINAL_GECCO83_DS.xlsx
    geccoplus: $input_base_dir/20211118_GECCOplus_final.xlsx
    json: $input_base_dir/gecco_definition.json
  kds_definition:
    json: $input_base_dir/kds_definition.json
    simplifier:
      modules:
        - https://fhir.simplifier.net/MedizininformatikInitiative-ModulPerson
        - https://fhir.simplifier.net/MedizininformatikInitiative-ModulFall
        - https://fhir.simplifier.net/MedizininformatikInitiative-ModulDiagnosen
        - https://fhir.simplifier.net/MedizininformatikInitiative-ModulProzeduren
        - https://fhir.simplifier.net/MedizininformatikInitiative-ModulMedikation
        - https://fhir.simplifier.net/MedizininformatikInitiative-modullabor
  dataset_definition: $input_base_dir/dataset_definitions.json
  categories_file: $input_base_dir/categories.json
  categories_excel_file: $input_base_dir/categories.xlsx
  files:
    hap: $input_base_dir/hap_test.xlsx
    pop: $input_base_dir/pop_test.xlsx
    suep: $input_base_dir/suep_test.xlsx
  table_definitions: $input_base_dir/table_definitions.json
  mappings: $input_base_dir/mappings/
output_dir: ../napkon-string-matching-data/output
cache_dir: ../napkon-string-matching-data/cache
