ARG BASE=python:3.10-alpine


FROM $BASE

LABEL org.opencontainers.image.description Base image having numpy and pandas already installed

WORKDIR /app

COPY requirements.txt .
RUN apk add --virtual build-dependencies build-base \
    && pip install $(grep "pandas\|numpy" requirements.txt) \
    && apk del build-dependencies
RUN apk add --no-cache libstdc++
