NOT_SPLIT_CHOICES = [
    ["Ja", "Nein", "Unbekannt"],
    ["Ja", "Nein", "Keine Informationen verfügbar"],
    ["pos", "neg"],
    [
        "Grad 1",
        "Grad 2",
        "Grad 3",
    ],
    [
        "Kaukasisch",
        "Afrikanisch",
        "Asiatisch",
        "Arabisch",
        "Latein-Amerikanisch",
        "gemischte ethnische Zugehörigkeit",
        "Andere",
    ],
    [
        "Männlich",
        "Weiblich",
        "Unbestimmt",
        "Divers",
        "keine Angabe",
    ],
    [
        "Keine",
        "Leichte Schwierigkeiten",
        "Einige Schwierigkeiten",
        "Große Schwierigkeiten",
        "Ich habe dies in den vergangenen 7 Tagen nicht gemacht",
    ],
    [
        "keine",
        "leichte",
        "mäßige",
        "starke",
        "extreme",
        "Keine Informationen verfügbar",
    ],
    [
        "Keine",
        "leichtgradige",
        "Mittelgradige",
        "Hochgradige",
        "Unbekannt (nicht bestimmbar)",
        "Nicht erhoben",
    ],
    [
        "Detected (qualifier value)",
        "Not detected (qualifier value)",
        "Inconclusive (qualifier value)",
    ],
    [
        "Mild (qualifier value)",
        "Moderate (severity modifier)",
        "Severe (severity modifier)",
        "Life threatening severity (qualifier value)",
    ],
    [
        "Typ 1",
        "Typ 2 ohne Insulin",
        "Typ 2 mit Insulin",
        "Typ 3",
        "Nein",
        "Unbekannt",
    ],
    [
        "Aktiv",
        "in Remission",
        "Nein",
        "Unbekannt",
    ],
    [
        "Ja",
        "Nichtraucher",
        "ehemaliger Raucher",
        "Unbekannt",
    ],
    [
        "Mit Hämodialyse",
        "ohne Hämodialyse",
        "Nein",
        "Unbekannt",
        "Schweregrad",
    ],
    [
        "Unspezifischer Befund",
        "COVID-typischer Befund",
        "Normalbefund",
    ],
    [
        "Sehr fit",
        "Durchscnittlich aktiv",
        "Gut zurechtkommend",
        "Vulnerabel",
        "Geringgradig frail",
        "Mittelgradig frail",
        "Ausgeprägt frail",
        "Extrem frail",
        "Terminal erkrankt",
    ],
    [
        "Phase ohne Komplikationen",
        "Phase mit Komplikationen",
        "Kritische Phase",
        "Genesungsphase",
        "Tod",
        "Unbekannt",
    ],
    [
        "Lebend entlassen",
        "Krankenhauseinweisung",
        "Überweisung in eine andere Einrichtung",
        "Tod",
        "Palliative Entlassung",
        "Nicht bekannt",
    ],
    [
        "pathologisch",
        "normal",
    ],
]
